# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0012_untranslated_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mp.Preference', verbose_name='preference'),
        ),
    ]
