# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0014_notification_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mp.Preference', verbose_name='preference'),
        ),
    ]
