# Generated by Django 2.1.5 on 2019-03-11 16:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0020_move_preference_items"),
    ]

    operations = [
        migrations.RemoveField(model_name="preference", name="price",),
        migrations.RemoveField(model_name="preference", name="quantity",),
        migrations.RemoveField(model_name="preference", name="title",),
    ]
